// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqA8ebPoQRJLfzbISmvoNzKGPnJ2HqR18',
    appId: '1:364815738039:web:75928f79d6ac7ddad75932',
    messagingSenderId: '364815738039',
    projectId: 'qwique',
    authDomain: 'qwique.firebaseapp.com',
    storageBucket: 'qwique.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXcTwIqKBsJ9XYhJBCvNaidThMGE9nBp8',
    appId: '1:364815738039:android:cd39963baa1bd1b7d75932',
    messagingSenderId: '364815738039',
    projectId: 'qwique',
    storageBucket: 'qwique.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSHozCeQWeD33VZhz7CiWypwi3k5K7iuI',
    appId: '1:364815738039:ios:ea0fa06cb811be6cd75932',
    messagingSenderId: '364815738039',
    projectId: 'qwique',
    storageBucket: 'qwique.appspot.com',
    iosClientId: '364815738039-bfi4395k5ukqtkjp603qrahsrmpo591j.apps.googleusercontent.com',
    iosBundleId: 'com.example.qwique',
  );
}
